version: 0.1
phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - npm i -g @angular/cli
      - npm install
      - npm install dotenv --save
      - npm install pm2 -g
      - sed -i 's@abc@'"$MONGODB_URI"'@' .env
      - echo `$MONGODB_URI` 
      - sed -i -e 's/\r$//' start_server.sh
      - sed -i -e 's/\r$//' stop_server.sh
      - chmod +x start_server.sh
      - chmod +x stop_server.sh   
artifacts:
  files:
    - appspec.yml
    - '**/*'